// https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/10001/2025-06-02?key=CZZMY9ZZUTFKF8EZ69CZJF9WQ&include=hours

export const weatherData2 = {
    "queryCost": 1,
    "latitude": 40.750742,
    "longitude": -73.99653,
    "resolvedAddress": "10001, USA",
    "address": "10001",
    "timezone": "America/New_York",
    "tzoffset": -4.0,
    "days": [
        {
            "datetime": "2025-06-02",
            "datetimeEpoch": 1748836800,
            "tempmax": 72.8,
            "tempmin": 56.2,
            "temp": 64.9,
            "feelslikemax": 72.8,
            "feelslikemin": 56.2,
            "feelslike": 64.9,
            "dew": 46.1,
            "humidity": 51.7,
            "precip": 0.197,
            "precipprob": 8.0,
            "precipcover": 12.5,
            "preciptype": [
                "rain"
            ],
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 13.6,
            "windspeed": 8.9,
            "winddir": 252.4,
            "pressure": 1013.0,
            "cloudcover": 24.6,
            "visibility": 14.6,
            "solarradiation": 359.8,
            "solarenergy": 31.1,
            "uvindex": 8.0,
            "severerisk": 10.0,
            "sunrise": "05:26:30",
            "sunriseEpoch": 1748856390,
            "sunset": "20:22:07",
            "sunsetEpoch": 1748910127,
            "moonphase": 0.25,
            "conditions": "Partially cloudy",
            "description": "Partly cloudy throughout the day.",
            "icon": "partly-cloudy-day",
            "stations": null,
            "source": "fcst",
            "hours": [
                {
                    "datetime": "00:00:00",
                    "datetimeEpoch": 1748836800,
                    "temp": 60.2,
                    "feelslike": 60.2,
                    "humidity": 59.36,
                    "dew": 45.9,
                    "precip": 0.0,
                    "precipprob": 5.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.9,
                    "windspeed": 5.1,
                    "winddir": 240.0,
                    "pressure": 1011.0,
                    "visibility": 15.0,
                    "cloudcover": 36.3,
                    "solarradiation": 1.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 3.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "01:00:00",
                    "datetimeEpoch": 1748840400,
                    "temp": 59.3,
                    "feelslike": 59.3,
                    "humidity": 61.71,
                    "dew": 46.1,
                    "precip": 0.0,
                    "precipprob": 5.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.7,
                    "windspeed": 4.7,
                    "winddir": 240.0,
                    "pressure": 1011.0,
                    "visibility": 15.0,
                    "cloudcover": 35.7,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 3.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "02:00:00",
                    "datetimeEpoch": 1748844000,
                    "temp": 58.6,
                    "feelslike": 58.6,
                    "humidity": 63.32,
                    "dew": 46.1,
                    "precip": 0.016,
                    "precipprob": 5.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": [
                        "rain"
                    ],
                    "windgust": 8.3,
                    "windspeed": 4.5,
                    "winddir": 240.0,
                    "pressure": 1012.0,
                    "visibility": 15.0,
                    "cloudcover": 35.0,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "03:00:00",
                    "datetimeEpoch": 1748847600,
                    "temp": 57.8,
                    "feelslike": 57.8,
                    "humidity": 64.53,
                    "dew": 45.9,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.3,
                    "windspeed": 4.5,
                    "winddir": 246.7,
                    "pressure": 1012.0,
                    "visibility": 15.0,
                    "cloudcover": 30.7,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "04:00:00",
                    "datetimeEpoch": 1748851200,
                    "temp": 56.9,
                    "feelslike": 56.9,
                    "humidity": 65.76,
                    "dew": 45.6,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.1,
                    "windspeed": 4.5,
                    "winddir": 253.3,
                    "pressure": 1012.0,
                    "visibility": 15.0,
                    "cloudcover": 26.3,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "05:00:00",
                    "datetimeEpoch": 1748854800,
                    "temp": 56.2,
                    "feelslike": 56.2,
                    "humidity": 67.03,
                    "dew": 45.4,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.1,
                    "windspeed": 4.5,
                    "winddir": 260.0,
                    "pressure": 1012.0,
                    "visibility": 15.0,
                    "cloudcover": 22.0,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "06:00:00",
                    "datetimeEpoch": 1748858400,
                    "temp": 57.5,
                    "feelslike": 57.5,
                    "humidity": 64.05,
                    "dew": 45.4,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.3,
                    "windspeed": 4.7,
                    "winddir": 270.0,
                    "pressure": 1013.0,
                    "visibility": 15.0,
                    "cloudcover": 18.7,
                    "solarradiation": 25.0,
                    "solarenergy": 0.1,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "07:00:00",
                    "datetimeEpoch": 1748862000,
                    "temp": 58.6,
                    "feelslike": 58.6,
                    "humidity": 61.62,
                    "dew": 45.4,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.5,
                    "windspeed": 5.1,
                    "winddir": 280.0,
                    "pressure": 1014.0,
                    "visibility": 15.0,
                    "cloudcover": 15.3,
                    "solarradiation": 50.0,
                    "solarenergy": 0.2,
                    "uvindex": 1.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "08:00:00",
                    "datetimeEpoch": 1748865600,
                    "temp": 59.8,
                    "feelslike": 59.8,
                    "humidity": 58.9,
                    "dew": 45.4,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.7,
                    "windspeed": 5.4,
                    "winddir": 290.0,
                    "pressure": 1014.0,
                    "visibility": 15.0,
                    "cloudcover": 12.0,
                    "solarradiation": 75.0,
                    "solarenergy": 0.3,
                    "uvindex": 1.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "09:00:00",
                    "datetimeEpoch": 1748869200,
                    "temp": 62.3,
                    "feelslike": 62.3,
                    "humidity": 53.51,
                    "dew": 45.2,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.4,
                    "windspeed": 6.0,
                    "winddir": 283.3,
                    "pressure": 1014.0,
                    "visibility": 15.0,
                    "cloudcover": 14.3,
                    "solarradiation": 274.0,
                    "solarenergy": 1.0,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "10:00:00",
                    "datetimeEpoch": 1748872800,
                    "temp": 65.0,
                    "feelslike": 65.0,
                    "humidity": 48.02,
                    "dew": 44.9,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 9.8,
                    "windspeed": 6.5,
                    "winddir": 276.7,
                    "pressure": 1014.0,
                    "visibility": 15.0,
                    "cloudcover": 16.7,
                    "solarradiation": 473.0,
                    "solarenergy": 1.7,
                    "uvindex": 5.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "11:00:00",
                    "datetimeEpoch": 1748876400,
                    "temp": 67.6,
                    "feelslike": 67.6,
                    "humidity": 43.7,
                    "dew": 44.7,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 10.5,
                    "windspeed": 7.2,
                    "winddir": 270.0,
                    "pressure": 1014.0,
                    "visibility": 15.0,
                    "cloudcover": 19.0,
                    "solarradiation": 672.0,
                    "solarenergy": 2.4,
                    "uvindex": 7.0,
                    "severerisk": 10.0,
                    "conditions": "Clear",
                    "icon": "clear-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "12:00:00",
                    "datetimeEpoch": 1748880000,
                    "temp": 69.2,
                    "feelslike": 69.2,
                    "humidity": 41.62,
                    "dew": 44.9,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 11.6,
                    "windspeed": 7.8,
                    "winddir": 263.3,
                    "pressure": 1014.0,
                    "visibility": 15.0,
                    "cloudcover": 21.3,
                    "solarradiation": 719.0,
                    "solarenergy": 2.6,
                    "uvindex": 7.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "13:00:00",
                    "datetimeEpoch": 1748883600,
                    "temp": 71.0,
                    "feelslike": 71.0,
                    "humidity": 39.68,
                    "dew": 45.2,
                    "precip": 0.0,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 12.5,
                    "windspeed": 8.3,
                    "winddir": 256.7,
                    "pressure": 1014.0,
                    "visibility": 15.0,
                    "cloudcover": 23.7,
                    "solarradiation": 765.0,
                    "solarenergy": 2.8,
                    "uvindex": 8.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "14:00:00",
                    "datetimeEpoch": 1748887200,
                    "temp": 72.6,
                    "feelslike": 72.6,
                    "humidity": 37.82,
                    "dew": 45.4,
                    "precip": 0.102,
                    "precipprob": 4.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": [
                        "rain"
                    ],
                    "windgust": 13.6,
                    "windspeed": 8.9,
                    "winddir": 250.0,
                    "pressure": 1013.0,
                    "visibility": 15.0,
                    "cloudcover": 26.0,
                    "solarradiation": 812.0,
                    "solarenergy": 2.9,
                    "uvindex": 8.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "15:00:00",
                    "datetimeEpoch": 1748890800,
                    "temp": 72.6,
                    "feelslike": 72.6,
                    "humidity": 37.82,
                    "dew": 45.4,
                    "precip": 0.0,
                    "precipprob": 5.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 13.4,
                    "windspeed": 8.7,
                    "winddir": 246.7,
                    "pressure": 1013.0,
                    "visibility": 15.0,
                    "cloudcover": 26.0,
                    "solarradiation": 804.0,
                    "solarenergy": 2.9,
                    "uvindex": 8.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "16:00:00",
                    "datetimeEpoch": 1748894400,
                    "temp": 72.8,
                    "feelslike": 72.8,
                    "humidity": 37.85,
                    "dew": 45.6,
                    "precip": 0.0,
                    "precipprob": 5.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 13.2,
                    "windspeed": 8.3,
                    "winddir": 243.3,
                    "pressure": 1012.0,
                    "visibility": 15.0,
                    "cloudcover": 26.0,
                    "solarradiation": 796.0,
                    "solarenergy": 2.9,
                    "uvindex": 8.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "17:00:00",
                    "datetimeEpoch": 1748898000,
                    "temp": 72.8,
                    "feelslike": 72.8,
                    "humidity": 37.85,
                    "dew": 45.6,
                    "precip": 0.0,
                    "precipprob": 5.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 13.0,
                    "windspeed": 8.1,
                    "winddir": 240.0,
                    "pressure": 1012.0,
                    "visibility": 15.0,
                    "cloudcover": 26.0,
                    "solarradiation": 788.0,
                    "solarenergy": 2.8,
                    "uvindex": 8.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "18:00:00",
                    "datetimeEpoch": 1748901600,
                    "temp": 71.5,
                    "feelslike": 71.5,
                    "humidity": 40.87,
                    "dew": 46.5,
                    "precip": 0.0,
                    "precipprob": 5.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 11.9,
                    "windspeed": 7.2,
                    "winddir": 236.7,
                    "pressure": 1012.0,
                    "visibility": 15.0,
                    "cloudcover": 24.7,
                    "solarradiation": 702.0,
                    "solarenergy": 2.5,
                    "uvindex": 7.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "19:00:00",
                    "datetimeEpoch": 1748905200,
                    "temp": 70.1,
                    "feelslike": 70.1,
                    "humidity": 44.1,
                    "dew": 47.2,
                    "precip": 0.0,
                    "precipprob": 5.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 11.0,
                    "windspeed": 6.3,
                    "winddir": 233.3,
                    "pressure": 1013.0,
                    "visibility": 15.0,
                    "cloudcover": 23.3,
                    "solarradiation": 616.0,
                    "solarenergy": 2.2,
                    "uvindex": 6.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "20:00:00",
                    "datetimeEpoch": 1748908800,
                    "temp": 68.8,
                    "feelslike": 68.8,
                    "humidity": 47.62,
                    "dew": 48.1,
                    "precip": 0.079,
                    "precipprob": 5.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": [
                        "rain"
                    ],
                    "windgust": 9.8,
                    "windspeed": 5.4,
                    "winddir": 230.0,
                    "pressure": 1013.0,
                    "visibility": 15.0,
                    "cloudcover": 22.0,
                    "solarradiation": 530.0,
                    "solarenergy": 1.9,
                    "uvindex": 5.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "21:00:00",
                    "datetimeEpoch": 1748912400,
                    "temp": 67.2,
                    "feelslike": 67.2,
                    "humidity": 51.03,
                    "dew": 48.5,
                    "precip": 0.0,
                    "precipprob": 8.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.9,
                    "windspeed": 5.1,
                    "winddir": 233.3,
                    "pressure": 1014.0,
                    "visibility": 15.0,
                    "cloudcover": 26.0,
                    "solarradiation": 354.0,
                    "solarenergy": 1.3,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "22:00:00",
                    "datetimeEpoch": 1748916000,
                    "temp": 65.6,
                    "feelslike": 65.6,
                    "humidity": 55.08,
                    "dew": 49.0,
                    "precip": 0.0,
                    "precipprob": 8.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 8.1,
                    "windspeed": 4.7,
                    "winddir": 236.7,
                    "pressure": 1014.0,
                    "visibility": 9.4,
                    "cloudcover": 30.0,
                    "solarradiation": 177.0,
                    "solarenergy": 0.6,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "23:00:00",
                    "datetimeEpoch": 1748919600,
                    "temp": 63.9,
                    "feelslike": 63.9,
                    "humidity": 59.07,
                    "dew": 49.4,
                    "precip": 0.0,
                    "precipprob": 8.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 7.2,
                    "windspeed": 4.5,
                    "winddir": 240.0,
                    "pressure": 1014.0,
                    "visibility": 10.9,
                    "cloudcover": 34.0,
                    "solarradiation": 1.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                }
            ]
        }
    ]
}