// entire url = 
// https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/10001/2025-06-01T08:00:00/2025-06-01T12:00:00?key=CZZMY9ZZUTFKF8EZ69CZJF9WQ&include=hours
import type { WeatherResponse } from "./weather-types";

export const weatherData: WeatherResponse = {
    "queryCost": 1,
    "latitude": 40.750742,
    "longitude": -73.99653,
    "resolvedAddress": "10001, USA",
    "address": "10001",
    "timezone": "America/New_York",
    "tzoffset": -4.0,
    "days": [
        {
            "datetime": "2025-06-01",
            "datetimeEpoch": 1748750400,
            "tempmax": 68.1,
            "tempmin": 54.2,
            "temp": 61.5,
            "feelslikemax": 68.1,
            "feelslikemin": 54.2,
            "feelslike": 61.5,
            "dew": 45.6,
            "humidity": 57.5,
            "precip": 0.094,
            "precipprob": 77.0,
            "precipcover": 4.17,
            "preciptype": [
                "rain"
            ],
            "snow": 0.0,
            "snowdepth": 0.0,
            "windgust": 21.0,
            "windspeed": 13.9,
            "winddir": 276.5,
            "pressure": 1005.5,
            "cloudcover": 42.7,
            "visibility": 11.9,
            "solarradiation": 242.4,
            "solarenergy": 21.0,
            "uvindex": 7.0,
            "severerisk": 10.0,
            "sunrise": "05:26:55",
            "sunriseEpoch": 1748770015,
            "sunset": "20:21:24",
            "sunsetEpoch": 1748823684,
            "moonphase": 0.18,
            "conditions": "Rain, Partially cloudy",
            "description": "Partly cloudy throughout the day with a chance of rain.",
            "icon": "rain",
            "stations": null,
            "source": "fcst",
            "hours": [
                {
                    "datetime": "00:00:00",
                    "datetimeEpoch": 1748750400,
                    "temp": 58.0,
                    "feelslike": 58.0,
                    "humidity": 74.39,
                    "dew": 49.9,
                    "precip": 0.0,
                    "precipprob": 77.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": [
                        "rain"
                    ],
                    "windgust": 16.3,
                    "windspeed": 9.8,
                    "winddir": 296.7,
                    "pressure": 1000.0,
                    "visibility": 10.1,
                    "cloudcover": 66.7,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Rain, Partially cloudy",
                    "icon": "rain",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "01:00:00",
                    "datetimeEpoch": 1748754000,
                    "temp": 57.3,
                    "feelslike": 57.3,
                    "humidity": 74.32,
                    "dew": 49.2,
                    "precip": 0.0,
                    "precipprob": 77.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": [
                        "rain"
                    ],
                    "windgust": 16.3,
                    "windspeed": 9.8,
                    "winddir": 293.3,
                    "pressure": 999.0,
                    "visibility": 10.1,
                    "cloudcover": 59.3,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Rain, Partially cloudy",
                    "icon": "rain",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "02:00:00",
                    "datetimeEpoch": 1748757600,
                    "temp": 56.7,
                    "feelslike": 56.7,
                    "humidity": 73.77,
                    "dew": 48.5,
                    "precip": 0.0,
                    "precipprob": 77.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": [
                        "rain"
                    ],
                    "windgust": 16.3,
                    "windspeed": 9.8,
                    "winddir": 290.0,
                    "pressure": 1000.0,
                    "visibility": 10.1,
                    "cloudcover": 52.0,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Rain, Partially cloudy",
                    "icon": "rain",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "03:00:00",
                    "datetimeEpoch": 1748761200,
                    "temp": 55.8,
                    "feelslike": 55.8,
                    "humidity": 74.18,
                    "dew": 47.7,
                    "precip": 0.0,
                    "precipprob": 41.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 16.6,
                    "windspeed": 10.1,
                    "winddir": 286.7,
                    "pressure": 1000.0,
                    "visibility": 10.1,
                    "cloudcover": 48.0,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "04:00:00",
                    "datetimeEpoch": 1748764800,
                    "temp": 55.1,
                    "feelslike": 55.1,
                    "humidity": 74.11,
                    "dew": 47.0,
                    "precip": 0.0,
                    "precipprob": 41.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 17.0,
                    "windspeed": 10.5,
                    "winddir": 283.3,
                    "pressure": 1000.0,
                    "visibility": 10.1,
                    "cloudcover": 44.0,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "05:00:00",
                    "datetimeEpoch": 1748768400,
                    "temp": 54.2,
                    "feelslike": 54.2,
                    "humidity": 74.53,
                    "dew": 46.3,
                    "precip": 0.0,
                    "precipprob": 41.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 17.2,
                    "windspeed": 10.7,
                    "winddir": 280.0,
                    "pressure": 1001.0,
                    "visibility": 10.1,
                    "cloudcover": 40.0,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "06:00:00",
                    "datetimeEpoch": 1748772000,
                    "temp": 55.1,
                    "feelslike": 55.1,
                    "humidity": 72.12,
                    "dew": 46.3,
                    "precip": 0.0,
                    "precipprob": 41.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 17.7,
                    "windspeed": 11.0,
                    "winddir": 280.0,
                    "pressure": 1003.0,
                    "visibility": 10.1,
                    "cloudcover": 34.7,
                    "solarradiation": 24.0,
                    "solarenergy": 0.1,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "07:00:00",
                    "datetimeEpoch": 1748775600,
                    "temp": 56.0,
                    "feelslike": 56.0,
                    "humidity": 69.81,
                    "dew": 46.3,
                    "precip": 0.0,
                    "precipprob": 41.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 18.3,
                    "windspeed": 11.4,
                    "winddir": 280.0,
                    "pressure": 1004.0,
                    "visibility": 10.1,
                    "cloudcover": 29.3,
                    "solarradiation": 49.0,
                    "solarenergy": 0.2,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "08:00:00",
                    "datetimeEpoch": 1748779200,
                    "temp": 56.9,
                    "feelslike": 56.9,
                    "humidity": 67.57,
                    "dew": 46.3,
                    "precip": 0.0,
                    "precipprob": 41.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 18.8,
                    "windspeed": 11.6,
                    "winddir": 280.0,
                    "pressure": 1005.0,
                    "visibility": 10.1,
                    "cloudcover": 24.0,
                    "solarradiation": 73.0,
                    "solarenergy": 0.3,
                    "uvindex": 1.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "09:00:00",
                    "datetimeEpoch": 1748782800,
                    "temp": 59.1,
                    "feelslike": 59.1,
                    "humidity": 61.27,
                    "dew": 45.8,
                    "precip": 0.0,
                    "precipprob": 16.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 19.2,
                    "windspeed": 12.3,
                    "winddir": 280.0,
                    "pressure": 1005.0,
                    "visibility": 10.1,
                    "cloudcover": 26.0,
                    "solarradiation": 270.0,
                    "solarenergy": 1.0,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "10:00:00",
                    "datetimeEpoch": 1748786400,
                    "temp": 61.4,
                    "feelslike": 61.4,
                    "humidity": 55.23,
                    "dew": 45.2,
                    "precip": 0.0,
                    "precipprob": 16.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 19.5,
                    "windspeed": 12.8,
                    "winddir": 280.0,
                    "pressure": 1006.0,
                    "visibility": 10.1,
                    "cloudcover": 28.0,
                    "solarradiation": 466.0,
                    "solarenergy": 1.7,
                    "uvindex": 5.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "11:00:00",
                    "datetimeEpoch": 1748790000,
                    "temp": 63.6,
                    "feelslike": 63.6,
                    "humidity": 50.15,
                    "dew": 44.7,
                    "precip": 0.0,
                    "precipprob": 16.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 19.9,
                    "windspeed": 13.4,
                    "winddir": 280.0,
                    "pressure": 1006.0,
                    "visibility": 10.1,
                    "cloudcover": 30.0,
                    "solarradiation": 663.0,
                    "solarenergy": 2.4,
                    "uvindex": 7.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "12:00:00",
                    "datetimeEpoch": 1748793600,
                    "temp": 64.7,
                    "feelslike": 64.7,
                    "humidity": 48.29,
                    "dew": 44.7,
                    "precip": 0.0,
                    "precipprob": 16.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 20.4,
                    "windspeed": 13.6,
                    "winddir": 276.7,
                    "pressure": 1006.0,
                    "visibility": 10.1,
                    "cloudcover": 38.0,
                    "solarradiation": 647.0,
                    "solarenergy": 2.3,
                    "uvindex": 6.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "13:00:00",
                    "datetimeEpoch": 1748797200,
                    "temp": 65.7,
                    "feelslike": 65.7,
                    "humidity": 46.19,
                    "dew": 44.5,
                    "precip": 0.0,
                    "precipprob": 16.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 20.6,
                    "windspeed": 13.6,
                    "winddir": 273.3,
                    "pressure": 1007.0,
                    "visibility": 10.1,
                    "cloudcover": 46.0,
                    "solarradiation": 630.0,
                    "solarenergy": 2.3,
                    "uvindex": 6.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "14:00:00",
                    "datetimeEpoch": 1748800800,
                    "temp": 66.8,
                    "feelslike": 66.8,
                    "humidity": 44.5,
                    "dew": 44.5,
                    "precip": 0.0,
                    "precipprob": 16.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 21.0,
                    "windspeed": 13.9,
                    "winddir": 270.0,
                    "pressure": 1007.0,
                    "visibility": 10.1,
                    "cloudcover": 54.0,
                    "solarradiation": 614.0,
                    "solarenergy": 2.2,
                    "uvindex": 6.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "15:00:00",
                    "datetimeEpoch": 1748804400,
                    "temp": 67.2,
                    "feelslike": 67.2,
                    "humidity": 43.35,
                    "dew": 44.1,
                    "precip": 0.0,
                    "precipprob": 6.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 20.6,
                    "windspeed": 13.6,
                    "winddir": 270.0,
                    "pressure": 1008.0,
                    "visibility": 15.0,
                    "cloudcover": 51.3,
                    "solarradiation": 511.0,
                    "solarenergy": 1.8,
                    "uvindex": 5.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "16:00:00",
                    "datetimeEpoch": 1748808000,
                    "temp": 67.7,
                    "feelslike": 67.7,
                    "humidity": 41.97,
                    "dew": 43.8,
                    "precip": 0.0,
                    "precipprob": 6.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 20.4,
                    "windspeed": 13.2,
                    "winddir": 270.0,
                    "pressure": 1008.0,
                    "visibility": 15.0,
                    "cloudcover": 48.7,
                    "solarradiation": 407.0,
                    "solarenergy": 1.5,
                    "uvindex": 4.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "17:00:00",
                    "datetimeEpoch": 1748811600,
                    "temp": 68.1,
                    "feelslike": 68.1,
                    "humidity": 40.88,
                    "dew": 43.4,
                    "precip": 0.0,
                    "precipprob": 6.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 19.9,
                    "windspeed": 13.0,
                    "winddir": 270.0,
                    "pressure": 1008.0,
                    "visibility": 15.0,
                    "cloudcover": 46.0,
                    "solarradiation": 304.0,
                    "solarenergy": 1.1,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "18:00:00",
                    "datetimeEpoch": 1748815200,
                    "temp": 67.0,
                    "feelslike": 67.0,
                    "humidity": 43.02,
                    "dew": 43.8,
                    "precip": 0.0,
                    "precipprob": 6.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 17.7,
                    "windspeed": 11.4,
                    "winddir": 266.7,
                    "pressure": 1008.0,
                    "visibility": 15.0,
                    "cloudcover": 42.0,
                    "solarradiation": 298.0,
                    "solarenergy": 1.1,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "19:00:00",
                    "datetimeEpoch": 1748818800,
                    "temp": 66.1,
                    "feelslike": 66.1,
                    "humidity": 45.0,
                    "dew": 44.1,
                    "precip": 0.0,
                    "precipprob": 6.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 15.4,
                    "windspeed": 9.6,
                    "winddir": 263.3,
                    "pressure": 1008.0,
                    "visibility": 15.0,
                    "cloudcover": 38.0,
                    "solarradiation": 291.0,
                    "solarenergy": 1.0,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "20:00:00",
                    "datetimeEpoch": 1748822400,
                    "temp": 65.0,
                    "feelslike": 65.0,
                    "humidity": 47.36,
                    "dew": 44.5,
                    "precip": 0.094,
                    "precipprob": 6.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": [
                        "rain"
                    ],
                    "windgust": 13.2,
                    "windspeed": 8.1,
                    "winddir": 260.0,
                    "pressure": 1009.0,
                    "visibility": 15.0,
                    "cloudcover": 34.0,
                    "solarradiation": 285.0,
                    "solarenergy": 1.0,
                    "uvindex": 3.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-day",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "21:00:00",
                    "datetimeEpoch": 1748826000,
                    "temp": 63.8,
                    "feelslike": 63.8,
                    "humidity": 49.83,
                    "dew": 44.7,
                    "precip": 0.0,
                    "precipprob": 6.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 12.3,
                    "windspeed": 7.2,
                    "winddir": 263.3,
                    "pressure": 1010.0,
                    "visibility": 15.0,
                    "cloudcover": 41.0,
                    "solarradiation": 190.0,
                    "solarenergy": 0.7,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "22:00:00",
                    "datetimeEpoch": 1748829600,
                    "temp": 62.7,
                    "feelslike": 62.7,
                    "humidity": 52.47,
                    "dew": 45.0,
                    "precip": 0.0,
                    "precipprob": 6.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 11.2,
                    "windspeed": 6.3,
                    "winddir": 266.7,
                    "pressure": 1011.0,
                    "visibility": 15.0,
                    "cloudcover": 48.0,
                    "solarradiation": 95.0,
                    "solarenergy": 0.3,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                },
                {
                    "datetime": "23:00:00",
                    "datetimeEpoch": 1748833200,
                    "temp": 61.4,
                    "feelslike": 61.4,
                    "humidity": 55.23,
                    "dew": 45.2,
                    "precip": 0.0,
                    "precipprob": 6.0,
                    "snow": 0.0,
                    "snowdepth": 0.0,
                    "preciptype": null,
                    "windgust": 10.3,
                    "windspeed": 5.4,
                    "winddir": 270.0,
                    "pressure": 1012.0,
                    "visibility": 15.0,
                    "cloudcover": 55.0,
                    "solarradiation": 0.0,
                    "solarenergy": 0.0,
                    "uvindex": 0.0,
                    "severerisk": 10.0,
                    "conditions": "Partially cloudy",
                    "icon": "partly-cloudy-night",
                    "stations": null,
                    "source": "fcst"
                }
            ]
        }
    ]
}